### PR TITLE
fix(pi-kilocode): let detectCompat auto-detect supportsDeveloperRole for kilocode models

### LINKED ISSUE #15: toPiModel hardcodes supportsDeveloperRole: false — causes different reasoning behaviour vs direct OpenRouter
## Problem

`toPiModel()` in `pi-kilocode/src/provider/models.ts` sets `supportsDeveloperRole: false` for every kilocode model. This overrides pi-ai's `detectCompat()` auto-detection, which would return `true` for the Kilo gateway URL (`https://api.kilo.ai/api/openrouter`).

The `developer` role is used by pi-ai for the system prompt on reasoning models. With `false`, pi sends:
```json
{"role": "system", "content": "..."}
```

Direct OpenRouter (same model) sends:
```json
{"role": "developer", "content": "..."}
```

This causes different thinking/reasoning behaviour for identical models and prompts depending on which provider is used.

## Verification

The Kilo gateway accepts `role: "developer"` — confirmed by sending a request directly to `https://api.kilo.ai/api/openrouter/chat/completions` with a developer-role system message: HTTP 200, valid response.

## Impact

Users switching between `--provider kilocode` and `--provider openrouter` for the same model (e.g. `qwen/qwen3.6-plus`) get different reasoning quality and style, with no obvious explanation.

## Suggested fix

Remove the `supportsDeveloperRole: false` override from `toPiModel()`. Let `detectCompat()` auto-detect the value from the provider baseUrl. The Kilo gateway is not in `detectCompat`'s `isNonStandard` list, so it correctly auto-detects as `true`.

Note: `supportsStore: false` and `thinkingFormat: "openrouter"` should remain as explicit overrides since `detectCompat` would get both wrong for the `kilo.ai` baseUrl.

### PR DESCRIPTION
**Pull request by iRonin**
Closes #15

## Problem

`toPiModel()` hardcodes `supportsDeveloperRole: false` for all kilocode models. This overrides pi-ai's `detectCompat()` auto-detection, which would return `true` for the Kilo gateway URL (not in `isNonStandard` list).

The result: kilocode sends the system prompt as `role: "system"` for reasoning models, while direct OpenRouter sends `role: "developer"` for the same model. This causes observably different thinking/reasoning behaviour.

## Verification

The Kilo gateway accepts `role: "developer"` — confirmed with a direct `curl` to `https://api.kilo.ai/api/openrouter/chat/completions`: HTTP 200, valid response.

## Fix

Remove the `supportsDeveloperRole: false` override so `detectCompat()` handles it automatically. `supportsStore: false` and `thinkingFormat: "openrouter"` are kept as explicit overrides since `detectCompat` would get both wrong for the `kilo.ai` baseUrl (`store` unsupported; `thinkingFormat` would default to `"openai"` not `"openrouter"`).

## Tests

Updated existing test to assert `supportsDeveloperRole === undefined` (not set by `toPiModel`) with a comment explaining that the resolved value (`true`) is computed later by pi-ai's `getCompat()` which merges explicit compat with `detectCompat()` output. 19/19 tests passing.

### CODE REVIEW

**Comment by sudosubin** [comment]
It seems like there are various changes mixed in the current branch. Could you please check it?

**Comment by iRonin** [comment]
Sure thing :) sorry about that I had Pi working on my local install with a few features in and most likely did not respect "create a clean PR" instructions. Let's blame it on Antrophic :)

**Comment by iRonin** [comment]
Thanks for catching that — you're right, the branch had gotten messy with merged-in changes from other PRs. I've force-pushed a clean branch from origin/main with only the single fix: removing the hardcoded `supportsDeveloperRole: false` override so detectCompat handles it automatically.

The diff is now 2 files, 2 insertions, 2 deletions. All tests pass.

File: pi-kilocode/src/provider/models.ts [hunk 1]
```diff
@@ -134,7 +134,8 @@ function toPiModel(m: KiloModel): ProviderModelConfig {
     contextWindow: m.context_length,
     maxTokens: maxOut ?? 8192,
     compat: {
-      supportsDeveloperRole: false,
+      // supportsDeveloperRole intentionally omitted — let pi-ai's detectCompat
+      // auto-detect from baseUrl. Expected: true (kilo.ai not in isNonStandard).
```
Comment (sudosubin) [inline pi-kilocode/src/provider/models.ts]: More concisely:

```suggestion
      // supportsDeveloperRole should be automatically inferred as true.
```

**Comment by sudosubin** [comment]
This PR was released in [pi-kilocode@0.1.2](https://github.com/sudosubin/pi-frontier/releases/tag/pi-kilocode%400.1.2) via commit 06c781b9b31a0687c2520af41c88861540b88944. Thank you again for the contribution.
